version: '3.9'

networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    container_name: algafood_mysql
    ports:
      - 3306:3306
    networks:
      - algafood-network
  app:
    image: algafood-api
    command:
      [
        './wait-for-it.sh',
        'algafood-mysql:3306',
        '-s',
        '--timeout=200',
        '--',
        'java',
        '-jar',
        'api.jar',
      ]
    environment:
      SPRING_PROFILES_ACTIVE: development
      DB_HOST: algafood-mysql
      spring.datasource.username: 'root'
      spring.datasource.password: ''
      spring.session.store-type: redis
      spring.redis.host: redis-server

    networks:
      - algafood-network
    depends_on:
      - algafood-mysql

  redis-server:
    image: redis:6.2.1-alpine
    networks:
      - algafood-network

  proxy_server:
    build: ./nginx
    image: nginx-proxy
    ports:
      - 80:80
    networks:
      - algafood-network
    depends_on:
      - app
