create table pedido (
	id bigint not null auto_increment primary key,
	sub_total decimal(19,2) not null,
	taxa_frete decimal(19,2) not null,
	valor_total decimal(19,2) not null,
	data_criacao datetime not null,
	data_confirmacao datetime,
	data_cancelamento datetime,
	data_entrega datetime,
	status varchar(11) not null,
	endereco_bairro varchar(255),
	endereco_cep varchar(255),
	endereco_complemento varchar(255),
	endereco_logradouro varchar(255),
	endereco_numero varchar(255),
	endereco_cidade_id bigint(20) not null,
	forma_pagamento_id bigint(20) not null,
	restaurante_id bigint(20) not null,
	cliente_id bigint(20)  not null,
	FOREIGN KEY (endereco_cidade_id) REFERENCES cidade(id),
	FOREIGN KEY (forma_pagamento_id) REFERENCES forma_pagamento(id),
	FOREIGN KEY (restaurante_id) REFERENCES restaurante(id),
	FOREIGN KEY (cliente_id) REFERENCES usuario(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;